version: "3.9"

services:
  #api:
    #build: .
    #ports:
      #- "8080:8080"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ugramdev
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_ROOT_PASSWORD: devrootpassword
    ports:
      - '3400:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: